### PR TITLE
Three features

### PR DESCRIPTION
**Pull request by Arthur-Milchior**
See each commit to see what each change does. A simple cherry picking would allow to take the one which you find interesting and leave the other one

### CODE REVIEW

**Comment by hssm** [comment]
Sorry for the delay, I've been quite busy lately.

1 - I'll merge this, seems fair. I normally keep my repos in one directory and symlink the add-on code into the add-on folder, but this lets us do both.

2 - I thought [I fixed this](https://github.com/hssm/advanced-browser/commit/f50dd4b3db5664d5ca309b219aed5af5df4363ff) a while ago. What problem is this trying to solve? How can I reproduce an error which this fixes?

3 - I'm fine with making all the columns sortable. Seems that your changes remove a bunch of the other ones though:

Original:
image
Yours:
image

**Comment by Arthur-Milchior** [comment]
2 - I fear it means I worked an outdated version of the code.
Actually, there is another problem I found, but which I didn't solve. 
Assume you have a note type NT, with a field F, and that you created a browser column for F. Then delete the note type NT. There is no way to remove the column F anymore. I believe it should be automatically removed if there are no more field.

**Comment by Arthur-Milchior** [comment]
3 - I can reproduce the bug. I can't explain it. It's pretty strange. All columns not sortable in anki did disappear. I'll look into it

**Comment by Arthur-Milchior** [comment]
I removed the useless commit from this branch, so now you only have commits which makes sens. I added back missing columns in the context menu

**Comment by Arthur-Milchior** [comment]
This last commit is not a feature. I think it corrects a bug I just had. But please fell free to discard it. I'm not sure at all what 'removedBuiltIns' is

**Comment by hssm** [comment]
I had a lot of trouble with these changes so it took a while to find the time and motivation to get it all working.

- The most recent commit for `cardEase` had syntax errors and used constants that don't exist
- `cardEase` sort doesn't work because it builds broken sql. I changed it to return a single value via python. New cards appear at the top, everything else is based on percentage (so 0% at top). I think that's what you intended.
- None of the `onData` functions are reachable because the built-in versions still take precedence since [they return data](https://github.com/hssm/advanced-browser/blob/master/advancedbrowser/advancedbrowser/core.py#L95). This is probably a good thing since we don't want to duplicate code. I've changed the functions to `None` to make it clear they do nothing.
- Sorting on Question or Answer can potentially execute hundreds of thousands of SQL queries. A single deck with 16k cards took me 30 seconds to search. There is no way to make these fast given their nature and is likely why they are disabled in the first place. I've removed them.

**Comment by Arthur-Milchior** [comment]
I am extremely sorry for the time I made you loose.
If something similar occurs again, please let me know and I'll  correct as fast as I can. 
I must admit I'm not (yet?) a good programmer, even if I'm learning.
Regarding the constants, I guess it meant I tested with my own version of anki, and not official anki, which was a mistake I try not to make anymoer. 

While I do admit that answers/questions takes a lot of time (and probably are not that useful by themselves), I still believe that being able to sort by note/card for example is really useful. And on my computer, my collection is sorted in less than a second. It's not extremly quick and I've almost 200 000 cards.

**Pull request merged**
