### PR TITLE
Update for 2.1.45

### LINKED ISSUE #123: 2.1.45 Alpha 1 -> add-on broken
image

**When opening the "Browse"**
image
https://www.reddit.com/r/Anki/comments/neoihx/anki_2145_alpha/ (changelogs)

### PR DESCRIPTION
**Pull request by RumovZ**
With this PR, advanced browser can be run on the ~latest~ next beta (2.1.45b~6~7). See 01cb415 for some reasoning. Also closes #125 and fixes #123.
What this PR *doesn't* do:
- Fix the editing functions (with the exception of flags, 49b44ad).
- Make use of new columns, which allow customising alignment, sort order etc.
- Use aggregated data in notes mode. Instead, the data for the first card of each note is shown.
- ~Fix an issue, where the headers are not restored correctly the first time. I intend to address this after https://github.com/ankitects/anki/pull/1277 has been merged, which will allow us to drop most of the remaining monkey patching.~

### CODE REVIEW

**Comment by hssm** [comment]
I'll try to look at this over the weekend.

**Comment by hssm** [comment]
Sorry for the delay. First, thanks for all of your recent work on Anki and for taking the time to update this add-on.

I have given your changes a test and things seem to work well so I'm happy to merge this and release it as-is.

One issue I've noticed is the presence of an 'Add-on' column when switching to note mode, even in a new profile.

---

Unfortunately, I don't have the time or the motivation to work on this add-on anytime soon, and the regular large changes recently have made me reluctant to sink any more time into it. At this point I'm willing to hand over ownership of the add-on if you or @Arthur-Milchior are interested in it. I don't think I'm the right person for this anymore.

Or perhaps it's a good time to consider adding the add-on's features into Anki itself.

**Comment by RumovZ** [comment]
> One issue I've noticed is the presence of an 'Add-on' column when switching to note mode, even in a new profile.

That's strange. Maybe that's from another add-on? Add-on columns can now be simply toggled off via the GUI. But before you do, you could look at the console output for `pp(self.col.get_config("advbrowse_activeNoteCols"))` to learn its identifier.

> At this point I'm willing to hand over ownership of the add-on if you or @Arthur-Milchior are interested in it.

That's a pity, but understandable, of course. I'm sure someone will take over, so your great work will continue to make Anki users happy.
I'm curious what Arthur will say.

> Or perhaps it's a good time to consider adding the add-on's features into Anki itself.

Let's ask @dae.

**Comment by Arthur-Milchior** [comment]
I'm fine with taking ownership. Obviously, I'm even more fine with having it incorporated into anki, and am willing to help doing so if @dae accepts. In any case, @dae , I'd appreciate if you could transfer the add-on ownership on ankiweb

**Comment by dae** [comment]
Would prefer to keep it separate for now; we can revisit that question in the future when there aren't so many other things going on. @ankingmed also expressed interest in possibly looking after it, so if you could work it out between the two of you and then get @hssm to confirm, I can transfer the add-on to whichever account you decide on.

Seconding Rumo's comments, thank you for all of the work you've put into this and your other add-ons @hssm!

**Comment by AnKingMed** [comment]
I'm happy to do whatever. What I would do is create a repo under anki palace and add @Arthur-Milchior to it. I've done this with Special Fields and it's been very easy to manage because I can publish the add-on after anyone works on it.   @Arthur-Milchior if you'd rather just takeover, I'm happy to do that as well

**Comment by hssm** [comment]
It's your call Arthur. I'm handing the add-on over to you; if you think it's easier to collaborate with @AnKingMed under anki palace (I will admit I don't know anything about this) then it's fine with me.

**Comment by Arthur-Milchior** [comment]
Fine for @AnKingMed 's ankipalace. Just discussed it with The AnKing, and I'm excited to see how it'll work.

**Comment by hssm** [comment]
Great. I've merged this commit. If you'd like me to upload a release I can do that, otherwise I'll leave the rest up to you guys.

**Comment by AnKingMed** [comment]
Can you transfer ownership of this repo to ankipalace?  I'll keep you added to it, but then I can control who to add to the repo

**Comment by hssm** [comment]
You mean https://github.com/ankipalace ?

**Comment by AnKingMed** [comment]
Yea that's the one

**Comment by hssm** [comment]
Tried:
> You don’t have the permission to create public repositories on ankipalace

**Comment by AnKingMed** [comment]
You should be able to just transfer ownership. https://docs.github.com/en/github/administering-a-repository/managing-repository-settings/transferring-a-repository

**Comment by hssm** [comment]
Seems there are limitations if it's to an organization:

> To transfer a repository that you own to an organization, you must have permission to create a repository in the target organization.

**Comment by AnKingMed** [comment]
Oh weird.  You can just transfer to me then and I'll do it.

**Pull request merged**
